backend:
  name: github
  branch: main
  repo: brattbikebus/info
  auth_scope: repo
  open_authoring: true

public_folder: "site/.vitepress/dist"
media_folder: "site/public"
publish_mode: editorial_workflow

collections:
  - name: "doc"
    label: "Content"
    folder: "site"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
